#!/usr/bin/env python3
"""UI icon set: Phosphor Fill SVGs -> the three icon headers the firmware uses.

  src/components/icons/listIcons.h          freeink::Icon, 24 + 32 px (file browser rows, toggles)
  src/components/icons/readerToolbarIcons.h freeink::Icon, 24 px (reader toolbar)
  src/components/icons/menuIcons.h          legacy drawIcon() bitmaps, 32 px (home menu, cover placeholder)

Sources: src/components/icons/phosphor/ (MIT) — or same-named SVGs in
src/components/icons/custom/ (gitignored), which take precedence, for an icon
set you are licensed to use but not to redistribute. Rasterizes with cairosvg.

    python3 scripts/gen_ui_icons.py
"""
import os
import subprocess
import sys
import tempfile

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICON_DIR = os.path.join(ROOT, "src", "components", "icons")
THRESHOLD = 128

# name used in C -> svg basename (searched in custom/, phosphor/, phosphor-regular/)
LIST_ICONS = [
    ("folder", "folder-fill"), ("file_text", "file-text-fill"), ("image", "image-fill"), ("book", "book-fill"),
    ("file", "file-fill"), ("wifi", "wifi-high-fill"), ("library", "books-fill"), ("radio_tower", "broadcast-fill"),
    ("sun", "sun"), ("moon", "moon"),  # outline: the frontlight toggle's "off" state
    ("sun_filled", "sun-fill"), ("moon_filled", "moon-fill"),
    ("upload", "upload-simple-fill"), ("download", "download-simple-fill"), ("bookmark", "bookmark-simple-fill"),
    ("usb", "usb-fill"), ("search", "magnifying-glass-fill"),
]
TOOLBAR_ICONS = [
    ("reader_contents", "list-fill"), ("reader_text", "text-t-fill"), ("reader_more", "dots-three-fill"),
    ("reader_back", "caret-left-fill"), ("reader_next", "caret-right-fill"),
]
# Legacy home-menu bitmaps: identifier -> svg (drawn by GfxRenderer::drawIcon)
MENU_ICONS = [
    ("FolderIcon", "folder-fill"), ("BookIcon", "book-fill"), ("RecentIcon", "clock-counter-clockwise-fill"),
    ("Settings2Icon", "gear-fill"), ("TransferIcon", "arrows-left-right-fill"), ("LibraryIcon", "books-fill"),
    ("WifiIcon", "wifi-high-fill"), ("HotspotIcon", "broadcast-fill"), ("BookmarkIcon", "bookmark-simple-fill"),
    ("CoverIcon", "image-square-fill"), ("TimerIcon", "timer-fill"),
]


def find_svg(base):
    for sub in ("custom", "phosphor", "phosphor-regular"):
        p = os.path.join(ICON_DIR, sub, base + ".svg")
        if os.path.exists(p):
            return p
    sys.exit(f"missing icon svg: {base}")


def rasterize(svg, px):
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        out = tmp.name
    try:
        subprocess.run(["cairosvg", svg, "-o", out, "-W", str(px), "-H", str(px)], check=True)
        img = Image.open(out).convert("RGBA")
        img.load()
    finally:
        os.unlink(out)
    bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    bg.paste(img, mask=img.split()[3])
    return bg.convert("L")


def ink(img, px):
    pix = img.load()
    return [[pix[x, y] < THRESHOLD for x in range(px)] for y in range(px)]


def pack_rows(rows, px):
    """freeink::Icon: MSB-first, bit 1 = transparent, bit 0 = ink; returns (bytes, opticalCenterY)."""
    data, sum_y, count = [], 0, 0
    for y in range(px):
        for xb in range(0, px, 8):
            byte = 0
            for b in range(8):
                x = xb + b
                white = 1
                if x < px and rows[y][x]:
                    white = 0
                    sum_y += y
                    count += 1
                byte |= white << (7 - b)
            data.append(byte)
    return data, (round(sum_y / count) if count else px // 2)


def pack_legacy(rows, px):
    """GfxRenderer::drawIcon layout: stored (r, c) lands on screen (x + px-1-r, y + c)."""
    data = []
    for r in range(px):
        for cb in range(0, px, 8):
            byte = 0
            for b in range(8):
                c = cb + b
                white = 1
                if c < px and rows[c][px - 1 - r]:
                    white = 0
                byte |= white << (7 - b)
            data.append(byte)
    return data


def pack_status(rows, px):
    """Status-bar glyphs: upright, row-major, MSB-first, bit 1 = ink (BaseTheme::drawBookmarkStatusIcon)."""
    data = []
    for y in range(px):
        for xb in range(0, px, 8):
            byte = 0
            for b in range(8):
                x = xb + b
                if x < px and rows[y][x]:
                    byte |= 1 << (7 - b)
            data.append(byte)
    return data


def fmt_bytes(data, per_line=18):
    return "\n".join("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + per_line]) + "," for i in range(0, len(data), per_line))


def write_icon_header(path, icons, sizes, note):
    out = ["#pragma once", "", "#include <Icon.h>", "", f"// Generated by scripts/gen_ui_icons.py ({note}). Do not edit.",
           f"// Sizes: {', '.join(map(str, sizes))}px. Icons: {len(icons)}.", ""]
    for ident, base in icons:
        svg = find_svg(base)
        src = os.path.relpath(svg, ICON_DIR).replace(os.sep, "/")
        out.append(f"// {ident}  ({src})")
        for px in sizes:
            bits, cy = pack_rows(ink(rasterize(svg, px), px), px)
            out.append(f"static const uint8_t icon_{ident}_{px}_bits[] = {{")
            out.append(fmt_bytes(bits))
            out.append("};")
            out.append(f"static const freeink::Icon icon_{ident}_{px} = {{{px}, {px}, {cy}, icon_{ident}_{px}_bits}};")
        out.append("")
    with open(path, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.relpath(path, ROOT)} ({len(icons)} icons)")


STATUS_ICONS = [("BookmarkStatusIcon", "bookmark-simple-fill", 16)]


def write_menu_header(path, icons, px):
    out = ["#pragma once", "", "#include <cstdint>", "",
           "// Generated by scripts/gen_ui_icons.py: home-menu icons in the pre-rotated 1-bpp",
           f"// layout GfxRenderer::drawIcon() expects ({px}x{px}), plus the upright bit-1-is-ink",
           "// status-bar glyphs. Do not edit.", ""]
    for ident, base, spx in STATUS_ICONS:
        svg = find_svg(base)
        out.append(f"// {ident}  ({os.path.relpath(svg, ICON_DIR).replace(os.sep, '/')}), size: {spx}x{spx}, bit 1 = ink")
        out.append(f"static const uint8_t {ident}[] = {{")
        out.append(fmt_bytes(pack_status(ink(rasterize(svg, spx), spx), spx)))
        out.append("};")
        out.append("")
    for ident, base in icons:
        svg = find_svg(base)
        src = os.path.relpath(svg, ICON_DIR).replace(os.sep, "/")
        out.append(f"// {ident}  ({src}), size: {px}x{px}")
        out.append(f"static const uint8_t {ident}[] = {{")
        out.append(fmt_bytes(pack_legacy(ink(rasterize(svg, px), px), px)))
        out.append("};")
        out.append("")
    with open(path, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.relpath(path, ROOT)} ({len(icons)} icons)")


write_icon_header(os.path.join(ICON_DIR, "listIcons.h"), LIST_ICONS, (24, 32), "Phosphor Icons, MIT")
write_icon_header(os.path.join(ICON_DIR, "readerToolbarIcons.h"), TOOLBAR_ICONS, (24,), "Phosphor Icons, MIT")
write_menu_header(os.path.join(ICON_DIR, "menuIcons.h"), MENU_ICONS, 32)
