#!/usr/bin/env python3
"""Home-widget icons: SVG -> freeink::Icon (1 bpp, 24 px) header.

Reads the filled Phosphor icons vendored in src/components/icons/phosphor/
(MIT) and writes src/components/icons/widgetIcons.h in the same format the
FreeInk SDK's gen_icons.py emits (bit 1 = transparent, bit 0 = ink, optical
center baked in). Rasterizes with cairosvg so no librsvg install is needed.

To use a different icon set (e.g. a licensed one you may not redistribute),
drop same-named SVGs into src/components/icons/custom/ (gitignored) — files
there take precedence over the Phosphor ones.

    python3 scripts/gen_widget_icons.py
"""
import os
import re
import subprocess
import sys
import tempfile

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICON_DIR = os.path.join(ROOT, "src", "components", "icons")
SIZE = 24
THRESHOLD = 128  # filled icons: plain 50% coverage cut keeps shapes solid

# identifier -> svg basename (without .svg)
ICONS = [
    ("clock", "clock-fill"),
    ("calendar", "calendar-blank-fill"),
    ("book_open", "book-open-fill"),
    ("calendar_dots", "calendar-dots-fill"),
    ("books", "books-fill"),
    ("book_bookmark", "book-bookmark-fill"),
    ("fire", "fire-fill"),
    ("chart_bar", "chart-bar-fill"),
    ("hourglass", "hourglass-medium-fill"),
    ("battery", "battery-high-fill"),
    ("sun", "sun-fill"),
    ("moon", "moon-fill"),
    ("cloud_sun", "cloud-sun-fill"),
    ("cloud_moon", "cloud-moon-fill"),
    ("cloud", "cloud-fill"),
    ("cloud_fog", "cloud-fog-fill"),
    ("cloud_rain", "cloud-rain-fill"),
    ("cloud_snow", "cloud-snow-fill"),
    ("cloud_lightning", "cloud-lightning-fill"),
]


def find_svg(basename):
    for sub in ("custom", "phosphor"):
        path = os.path.join(ICON_DIR, sub, basename + ".svg")
        if os.path.exists(path):
            return path
    sys.exit(f"missing icon svg: {basename}")


def rasterize(svg_path, px):
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        out_png = tmp.name
    try:
        subprocess.run(["cairosvg", svg_path, "-o", out_png, "-W", str(px), "-H", str(px)], check=True)
        img = Image.open(out_png).convert("RGBA")
        img.load()
    finally:
        os.unlink(out_png)
    bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    bg.paste(img, mask=img.split()[3])
    return bg.convert("L")


def pack(img, px):
    pix = img.load()
    data, sum_y, count = [], 0, 0
    for y in range(px):
        for xb in range(0, px, 8):
            byte = 0
            for b in range(8):
                x = xb + b
                white = 1
                if x < px and pix[x, y] < THRESHOLD:
                    white = 0
                    sum_y += y
                    count += 1
                byte |= white << (7 - b)
            data.append(byte)
    return data, (round(sum_y / count) if count else px // 2)


out = ["#pragma once", "", "#include <Icon.h>", "",
       "// Generated by scripts/gen_widget_icons.py from src/components/icons/phosphor (Phosphor",
       "// Icons, MIT) or src/components/icons/custom overrides. Do not edit.", ""]
for ident, base in ICONS:
    svg = find_svg(base)
    bits, cy = pack(rasterize(svg, SIZE), SIZE)
    src = os.path.relpath(svg, ICON_DIR).replace(os.sep, "/")
    out.append(f"// {ident}  ({src})")
    out.append(f"static const uint8_t widget_icon_{ident}_bits[] = {{")
    for i in range(0, len(bits), 18):
        out.append("    " + ", ".join(f"0x{b:02X}" for b in bits[i:i + 18]) + ",")
    out.append("};")
    out.append(f"static const freeink::Icon widget_icon_{ident} = {{{SIZE}, {SIZE}, {cy}, widget_icon_{ident}_bits}};")
    out.append("")
with open(os.path.join(ICON_DIR, "widgetIcons.h"), "w") as f:
    f.write("\n".join(out))
print(f"wrote widgetIcons.h ({len(ICONS)} icons, {SIZE}px)")
