// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_12_FONT_ID (778531645)
#define NOTOSERIF_14_FONT_ID (-928381217)
#define NOTOSERIF_16_FONT_ID (17214534)
#define NOTOSERIF_18_FONT_ID (840051567)
#define NOTOSANS_12_FONT_ID (1597191560)
#define NOTOSANS_14_FONT_ID (-1413326613)
#define NOTOSANS_16_FONT_ID (116566294)
#define NOTOSANS_18_FONT_ID (-348426591)
#define UI_10_FONT_ID (-288489466)
#define UI_12_FONT_ID (819343285)
#define SMALL_FONT_ID (-764225639)
#define HELVETICANEUE_14_FONT_ID (-1807121897)
#define HELVETICANEUE_24_FONT_ID (-815572960)
#define HELVETICANEUE_40_FONT_ID (-1763648028)
#define GEIST_14_FONT_ID (-1949064626)
#define GEIST_24_FONT_ID (1170080954)
#define GEIST_40_FONT_ID (-1166822798)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICANEUE_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICANEUE_24_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICANEUE_40_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(GEIST_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(GEIST_24_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(GEIST_40_FONT_ID != 0, "Font ID collision with sentinel");
